const cardsData = [
  {
    id: 0,
    brand: 'Vans',
    model: 'Filmore',
    color: 'black',
    size: '44.0',
    price: '5000.00',
    photo: '/vans/Filmore/black/angle1.webp',
  },
  {
    id: 1,
    brand: 'Vans',
    model: 'Filmore',
    color: 'blue',
    size: '44.0',
    price: '5000.00',
    photo: '/vans/Filmore/black/angle1.webp',
  },
  {
    id: 2,
    brand: 'Vans',
    model: 'Filmore',
    color: 'grey',
    size: '44.0',
    price: '6000.00',
    photo: '/vans/Filmore/black/angle1.webp',
  },
  {
    id: 3,
    brand: 'Vans',
    model: 'Filmore',
    color: 'black',
    size: '44.0',
    price: '5000.00',
    photo: '/vans/Filmore/blue/angle.webp',
  },
  {
    id: 4,
    brand: 'Vans',
    model: 'Filmore',
    color: 'blue',
    size: '44.0',
    price: '5000.00',
    photo: '/vans/Filmore/blue/angle.webp',
  },
  {
    id: 5,
    brand: 'Vans',
    model: 'Filmore',
    color: 'grey',
    size: '44.0',
    price: '6000.00',
    photo: '/vans/Filmore/blue/angle.webp',
  },
  {
    id: 6,
    brand: 'Vans',
    model: 'Filmore',
    color: 'black',
    size: '44.0',
    price: '5000.00',
    photo: '/vans/Filmore/grey/angle.webp',
  },
  {
    id: 7,
    brand: 'Vans',
    model: 'Filmore',
    color: 'blue',
    size: '44.0',
    price: '5000.00',
    photo: '/vans/Filmore/grey/angle.webp',
  },
  {
    id: 8,
    brand: 'Vans',
    model: 'Filmore',
    color: 'grey',
    size: '44.0',
    price: '6000.00',
    photo: '/vans/Filmore/grey/angle.webp',
  },
  {
    id: 9,
    brand: 'Vans',
    model: 'Old Skool',
    color: 'beige',
    size: '44.0',
    price: '5450.00',
    photo: '/vans/Old_Skool/beige/back-angle-double.webp',
  },
  {
    id: 10,
    brand: 'Vans',
    model: 'Old Skool',
    color: 'black-gum',
    size: '44.0',
    price: '5450.00',
    photo: '/vans/Old_Skool/beige/back-angle-double.webp',
  },
  {
    id: 11,
    brand: 'Vans',
    model: 'Old Skool',
    color: 'red',
    size: '44.0',
    price: '5200.00',
    photo: '/vans/Old_Skool/beige/back-angle-double.webp',
  },
]

export { cardsData }
