INSERT INTO sizes (size_value) 
VALUES
    (35),
    (35.5),
    (36),
    (36.5),
    (37),
    (37.5),
    (38),
    (38.5),
    (39),
    (39.5),
    (40),
    (40.5),
    (41),
    (41.5),
    (42),
    (42.5),
    (43),
    (43.5),
    (44),
    (44.5),
    (45);

INSERT INTO brands (brand_name)
VALUES
    ('Vans'),
    ('Nike SB'),
    ('DC Shoes');

INSERT INTO colors (color_name)
VALUES
    ('beige'),
    ('beige-gum'),
    ('black'),
    ('black-brown'),
    ('black-gum'),
    ('black-white'),
    ('blue'),
    ('brown'),
    ('brown-black'),
    ('green'),
    ('grey'),
    ('red'),
    ('white'),
    ('white-black'),
    ('white-red'),
    ('red-black'),
    ('yellow');

INSERT INTO models (article, model_name, brand_id)
VALUES
    ('VN0A3MTJ', 'Filmore', 1),
    ('VN0005UF', 'Old Skool', 1),
    ('VN000TUY', 'Atwood', 1),
    ('VN000CSP', 'Caldrone', 1),
    ('DM3493', 'Chron 2', 2),
    ('FJ1675', 'Stefan Janoski', 2),
    ('CJ0882', 'Alleyoop', 2),
    ('DV5477', 'Force 58', 2),
    ('ADYS100765', 'Manateca 4', 3),
    ('ADYS300739', 'Teknic', 3),
    ('303190', 'Anvil', 3),
    ('ADYS300591', 'Manual', 3),
    ('ADYS100647', 'Crisis 2', 3);

INSERT INTO model_colors (model_id, color_id, is_primary)
VALUES
    (1, 3, TRUE),
    (1, 7, FALSE),
    (1, 11, FALSE),
    (2, 17, FALSE),
    (2, 1, FALSE),
    (2, 5, TRUE),
    (2, 12, FALSE),
    (3, 1, FALSE),
    (3, 10, FALSE),
    (3, 3, TRUE),
    (4, 1, FALSE),
    (4, 10, FALSE),
    (4, 3, TRUE),
    (5, 5, FALSE),
    (5, 1, FALSE),
    (5, 7, FALSE),
    (5, 10, FALSE),
    (5, 13, FALSE),
    (5, 6, TRUE),
    (5, 2, FALSE),
    (6, 10, TRUE),
    (7, 16, TRUE),
    (8, 11, FALSE),
    (8, 8, FALES),
    (8, 10, FALSE),
    (8, 13, TRUE),
    (9, 13, FALES),
    (9, 8, FALSE),
    (9, 9, FALSE),
    (9, 11, FALSE),
    (9, 14, FALSE),
    (9, 15, FALSE),
    (9, 4, FALSE),
    (9, 3, TRUE),
    (10, 10, TRUE),
    (10, 7, FALSE),
    (11, 6, TRUE),
    (12, 5, TRUE),
    (13, 3, FALSE);

INSERT INTO photos (model_id, color_id, image_url, is_primary, alt_text)
VALUES
    (1, 3, '/vans/Filmore/black/angle.webp', FALSE, 'angle'), -- top, down, left, right, angle, angle-double, back-double, top-double, back-angle-double, angle-close(3), top-down(1), angle1(1), back-angle(1)
    (1, 3, '/vans/Filmore/black/angle1.webp', TRUE, 'angle1'),
    (1, 3, '/vans/Filmore/black/angle-close.webp', FALSE, 'angle-close'),
    (1, 3, '/vans/Filmore/black/back-angle.webp', FALSE, 'back-angle'),
    (1, 3, '/vans/Filmore/black/left.webp', FALSE, 'left'),
    (1, 3, '/vans/Filmore/black/top-down.webp', FALSE, 'top-down'),
    (1, 7, '/vans/Filmore/blue/angle.webp', TRUE, 'angle'),
    (1, 7, '/vans/Filmore/blue/angle-close.webp', FALSE, 'angle-close'),
    (1, 7, '/vans/Filmore/blue/down.webp', FALSE, 'down'),
    (1, 7, '/vans/Filmore/blue/left.webp', FALSE, 'left'),
    (1, 7, '/vans/Filmore/blue/right.webp', FALSE, 'right'),
    (1, 7, '/vans/Filmore/blue/top.webp', FALSE, 'top'),
    (1, 11, '/vans/Filmore/grey/angle.webp', TRUE, 'angle'),
    (1, 11, '/vans/Filmore/grey/angle-double.webp', FALSE, 'angle-double'),
    (1, 11, '/vans/Filmore/grey/down.webp', FALSE, 'down'),
    (1, 11, '/vans/Filmore/grey/left.webp', FALSE, 'left'),
    (1, 11, '/vans/Filmore/grey/right.webp', FALSE, 'right'),
    (1, 11, '/vans/Filmore/grey/top.webp', FALSE, 'top'),
    (2, 1, '/vans/Old_Skool/beige/angle-double.webp', FALSE, 'angle-double'),
    (2, 1, '/vans/Old_Skool/beige/back-angle-double.webp', TRUE, 'back-angle-double'),
    (2, 1, '/vans/Old_Skool/beige/down.webp', FALSE, 'down'),
    (2, 1, '/vans/Old_Skool/beige/left.webp', FALSE, 'left'),
    (2, 1, '/vans/Old_Skool/beige/right.webp', FALSE, 'right'),
    (2, 1, '/vans/Old_Skool/beige/top.webp', FALSE, 'top'),
    (2, 5, '/vans/Old_Skool/black-gum/angle-double.webp', TRUE, 'angle-double'),
    (2, 5, '/vans/Old_Skool/black-gum/back-angle-double.webp', FALSE, 'back-angle-double'),
    (2, 5, '/vans/Old_Skool/black-gum/down.webp', FALSE, 'down'),
    (2, 5, '/vans/Old_Skool/black-gum/left.webp', FALSE, 'left'),
    (2, 5, '/vans/Old_Skool/black-gum/right.webp', FALSE, 'right'),
    (2, 5, '/vans/Old_Skool/black-gum/top-double.webp', FALSE, 'top-double'),
    (2, 12, '/vans/Old_Skool/red/angle.webp', FALSE, 'angle'),
    (2, 12, '/vans/Old_Skool/red/left.webp', FALSE, 'left'),
    (2, 12, '/vans/Old_Skool/red/right.webp', TRUE, 'right'),
    (2, 12, '/vans/Old_Skool/red/top-double.webp', FALSE, 'top-double'),
    (2, 17, '/vans/Old_Skool/yellow/angle-close.webp', TRUE, 'angle-close'),
    (2, 17, '/vans/Old_Skool/yellow/angle-double.webp', FALSE, 'angle-double'),
    (2, 17, '/vans/Old_Skool/yellow/down.webp', FALSE, 'down'),
    (2, 17, '/vans/Old_Skool/yellow/left.webp', FALSE, 'left'),
    (2, 17, '/vans/Old_Skool/yellow/right.webp', FALSE, 'right'),
    (2, 17, '/vans/Old_Skool/yellow/top.webp', FALSE, 'top'),
    (3, 3, '/vans/Atwood/angle.webp', FALSE, 'angle'),
    (3, 3, '/vans/Atwood/angle-double.webp', FALSE, 'angle-double'),
    (3, 3, '/vans/Atwood/back-double.webp', TRUE, 'back-double'),
    (3, 3, '/vans/Atwood/down.webp', FALSE, 'down'),
    (3, 3, '/vans/Atwood/left.webp', FALSE, 'right'),
    (4, 1, '/vans/Caldrone/beige/angle-double.webp', FALSE, 'angle-double'),
    (4, 1, '/vans/Caldrone/beige/back-double.webp', FALSE, 'back-double'),
    (4, 1, '/vans/Caldrone/beige/down.webp', FALSE, 'down'),
    (4, 1, '/vans/Caldrone/beige/left.webp', TRUE, 'left'),
    (4, 1, '/vans/Caldrone/beige/right.webp', FALSE, 'right'),
    (4, 1, '/vans/Caldrone/beige/top-double.webp', FALSE, 'top-double'),
    (4, 3, '/vans/Caldrone/black/angle.webp', FALSE, 'angle'),
    (4, 3, '/vans/Caldrone/black/down.webp', FALSE, 'down'),
    (4, 3, '/vans/Caldrone/black/left.webp', TRUE, 'left'),
    (4, 3, '/vans/Caldrone/black/right.webp', FALSE, 'right'),
    (4, 3, '/vans/Caldrone/black/top.webp', FALSE, 'top'),
    (4, 10, '/vans/Caldrone/green/angle.webp', TRUE, 'angle'),
    (4, 10, '/vans/Caldrone/green/angle-double.webp', FALSE, 'angle-double'),
    (4, 10, '/vans/Caldrone/green/back-angle-double.webp', FALSE, 'back-angle-double'),
    (4, 10, '/vans/Caldrone/green/down.webp', FALSE, 'down'),
    (4, 10, '/vans/Caldrone/green/right.webp', FALSE, 'right'),
    (5, 1, '/nike/cron-2/beige/angle.webp', TRUE, 'angle'),
    (5, 1, '/nike/cron-2/beige/angle-double.webp', FALSE, 'angle-double'),
    (5, 1, '/nike/cron-2/beige/down.webp', FALSE, 'down'),
    (5, 1, '/nike/cron-2/beige/right.webp', FALSE, 'right'),
    (5, 1, '/nike/cron-2/beige/top-double.webp', FALSE, 'top-double'),
    (5, 2, '/nike/cron-2/beige-gum/angle-double.webp', TRUE, 'angle-double'),
    (5, 2, '/nike/cron-2/beige-gum/back-angle-double.webp', FALSE, 'back-angle-double'),
    (5, 2, '/nike/cron-2/beige-gum/down.webp', FALSE, 'down'),
    (5, 2, '/nike/cron-2/beige-gum/left.webp', FALSE, 'left'),
    (5, 2, '/nike/cron-2/beige-gum/top-double.webp', FALSE, 'top-double'),
    (5, 5, '/nike/cron-2/black-gum/angle.webp', FALSE, 'angle'),
    (5, 5, '/nike/cron-2/black-gum/angle-double.webp', TRUE, 'angle-double'),
    (5, 5, '/nike/cron-2/black-gum/down.webp', FALSE, 'down'),
    (5, 5, '/nike/cron-2/black-gum/left.webp', FALSE, 'left'),
    (5, 5, '/nike/cron-2/black-gum/right.webp', FALSE, 'right'),
    (5, 5, '/nike/cron-2/black-gum/top-double.webp', FALSE, 'top-double'),
    (5, 6, '/nike/cron-2/black-white/angle-double.webp', TRUE, 'angle-double'),
    (5, 6, '/nike/cron-2/black-white/back-angle-double.webp', FALSE, 'back-angle-double'),
    (5, 6, '/nike/cron-2/black-white/down.webp', FALSE, 'down'),
    (5, 6, '/nike/cron-2/black-white/left.webp', FALSE, 'left'),
    (5, 6, '/nike/cron-2/black-white/top-double.webp', FALSE, 'top-double'),
    (5, 7, '/nike/cron-2/blue/angle.webp', TRUE, 'angle'),
    (5, 7, '/nike/cron-2/blue/angle-double.webp', FALSE, 'angle-double'),
    (5, 7, '/nike/cron-2/blue/down.webp', FALSE, 'down'),
    (5, 7, '/nike/cron-2/blue/left.webp', FALSE, 'left'),
    (5, 7, '/nike/cron-2/blue/right.webp', FALSE, 'right'),
    (5, 7, '/nike/cron-2/blue/top-double.webp', FALSE, 'top-double'),
    (5, 10, '/nike/cron-2/green/angle.webp', TRUE, 'angle'),
    (5, 10, '/nike/cron-2/green/angle-double.webp', FALSE, 'angle-double'),
    (5, 10, '/nike/cron-2/green/back-angle-double.webp', FALSE, 'back-angle-double'),
    (5, 10, '/nike/cron-2/green/down.webp', FALSE, 'down'),
    (5, 10, '/nike/cron-2/green/right.webp', FALSE, 'right'),
    (5, 10, '/nike/cron-2/green/top.webp', FALSE, 'top'),
    (5, 13, '/nike/cron-2/white/angle.webp', FALSE, 'angle'),
    (5, 13, '/nike/cron-2/white/angle-close.webp', FALSE, 'angle-close'),
    (5, 13, '/nike/cron-2/white/angle-double.webp', FALSE, 'angle-double'),
    (5, 13, '/nike/cron-2/white/back-angle-double.webp', TRUE, 'back-angle-double'),
    (5, 13, '/nike/cron-2/white/down.webp', FALSE, 'down'),
    (5, 13, '/nike/cron-2/white/right.webp', FALSE, 'right'),
    (6, 10, '/nike/stefan-janoski/green/angle.webp', FALSE, 'angle'),
    (6, 10, '/nike/stefan-janoski/green/angle-double.webp', TRUE, 'angle-double'),
    (6, 10, '/nike/stefan-janoski/green/down.webp', FALSE, 'down'),
    (6, 10, '/nike/stefan-janoski/green/left.webp', FALSE, 'left'),
    (6, 10, '/nike/stefan-janoski/green/right.webp', FALSE, 'right'),
    (6, 10, '/nike/stefan-janoski/green/top-double.webp', FALSE, 'top-double'),
    (7, 16, '/nike/alleyoop/red-black/angle-double.webp', TRUE, 'angle-double'),
    (7, 16, '/nike/alleyoop/red-black/back-angle-double.webp', FALSE, 'back-angle-double'),
    (7, 16, '/nike/alleyoop/red-black/down.webp', FALSE, 'down'),
    (7, 16, '/nike/alleyoop/red-black/left.webp', FALSE, 'left'),
    (7, 16, '/nike/alleyoop/red-black/top-double.webp', FALSE, 'top-double'),
    (8, 8, '/nike/force58/brown/angle-double.webp', TRUE, 'angle-double'),
    (8, 8, '/nike/force58/brown/down.webp', FALSE, 'down'),
    (8, 8, '/nike/force58/brown/left.webp', FALSE, 'left'),
    (8, 8, '/nike/force58/brown/right.webp', FALSE, 'right'),
    (8, 8, '/nike/force58/brown/top-double.webp', FALSE, 'top-double'),
    (8, 10, '/nike/force58/green/angle-double.webp', TRUE, 'angle-double'),
    (8, 10, '/nike/force58/green/back-angle-double.webp', FALSE, 'back-angle-double'),
    (8, 10, '/nike/force58/green/down.webp', FALSE, 'down'),
    (8, 10, '/nike/force58/green/left.webp', FALSE, 'left'),
    (8, 10, '/nike/force58/green/top-double.webp', FALSE, 'top-double'),
    (8, 11, '/nike/force58/grey/angle.webp', TRUE, 'angle'),
    (8, 11, '/nike/force58/grey/angle-double.webp', FALSE, 'angle-double'),
    (8, 11, '/nike/force58/grey/down.webp', FALSE, 'down'),
    (8, 11, '/nike/force58/grey/left.webp', FALSE, 'left'),
    (8, 11, '/nike/force58/grey/right.webp', FALSE, 'right'),
    (8, 11, '/nike/force58/grey/top-double.webp', FALSE, 'top-double'),
    (8, 13, '/nike/force58/white/angle-double.webp', TRUE, 'angle-double'),
    (8, 13, '/nike/force58/white/back-angle-double.webp', FALSE, 'back-angle-double'),
    (8, 13, '/nike/force58/white/down.webp', FALSE, 'down'),
    (8, 13, '/nike/force58/white/left.webp', FALSE, 'left'),
    (8, 13, '/nike/force58/white/top-double.webp', FALSE, 'top-double'),
    (9, 3, '/dc/manteca4/black/angle.webp', TRUE, 'angle'),
    (9, 3, '/dc/manteca4/black/down.webp', FALSE, 'down'),
    (9, 3, '/dc/manteca4/black/left.webp', FALSE, 'left'),
    (9, 3, '/dc/manteca4/black/right.webp', FALSE, 'right'),
    (9, 3, '/dc/manteca4/black/top.webp', FALSE, 'top'),
    (9, 4, '/dc/manteca4/black-brown/down.webp', FALSE, 'down'),
    (9, 4, '/dc/manteca4/black-brown/left.webp', FALSE, 'left'),
    (9, 4, '/dc/manteca4/black-brown/right.webp', TRUE, 'right'),
    (9, 4, '/dc/manteca4/black-brown/top.webp', FALSE, 'top'),
    (9, 8, '/dc/manteca4/brown/angle.webp', TRUE, 'angle'),
    (9, 8, '/dc/manteca4/brown/angle-double.webp', FALSE, 'angle-double'),
    (9, 8, '/dc/manteca4/brown/back-double.webp', FALSE, 'back-double'),
    (9, 8, '/dc/manteca4/brown/down.webp', FALSE, 'down'),
    (9, 8, '/dc/manteca4/brown/left.webp', FALSE, 'left'),
    (9, 9, '/dc/manteca4/brown-black/angle.webp', TRUE, 'angle'),
    (9, 9, '/dc/manteca4/brown-black/angle-double.webp', FALSE, 'angle-double'),
    (9, 9, '/dc/manteca4/brown-black/back-double.webp', FALSE, 'back-double'),
    (9, 9, '/dc/manteca4/brown-black/down.webp', FALSE, 'down'),
    (9, 9, '/dc/manteca4/brown-black/left.webp', FALSE, 'left'),
    (9, 11, '/dc/manteca4/grey/angle.webp', TRUE, 'angle'),
    (9, 11, '/dc/manteca4/grey/angle-double.webp', FALSE, 'angle-double'),
    (9, 11, '/dc/manteca4/grey/back-double.webp', FALSE, 'back-double'),
    (9, 11, '/dc/manteca4/grey/down.webp', FALSE, 'down'),
    (9, 11, '/dc/manteca4/grey/left.webp', FALSE, 'left'),
    (9, 13, '/dc/manteca4/white/angle.webp', TRUE, 'angle'),
    (9, 13, '/dc/manteca4/white/angle-double.webp', FALSE, 'angle-double'),
    (9, 13, '/dc/manteca4/white/back-double.webp', FALSE, 'back-double'),
    (9, 13, '/dc/manteca4/white/down.webp', FALSE, 'down'),
    (9, 13, '/dc/manteca4/white/left.webp', FALSE, 'left'),
    (9, 14, '/dc/manteca4/white-black/angle-double.webp', TRUE, 'angle-double'),
    (9, 14, '/dc/manteca4/white-black/back-double.webp', FALSE, 'back-double'),
    (9, 14, '/dc/manteca4/white-black/down.webp', FALSE, 'down'),
    (9, 14, '/dc/manteca4/white-black/left.webp', FALSE, 'left'),
    (9, 14, '/dc/manteca4/white-black/right.webp', FALSE, 'right'),
    (9, 14, '/dc/manteca4/white-black/top.webp', FALSE, 'top'),
    (9, 15, '/dc/manteca4/white-red/angle-double.webp', TRUE, 'angle-double'),
    (9, 15, '/dc/manteca4/white-red/todownp.webp', FALSE, 'down'),
    (9, 15, '/dc/manteca4/white-red/left.webp', FALSE, 'left'),
    (9, 15, '/dc/manteca4/white-red/right.webp', FALSE, 'right'),
    (9, 15, '/dc/manteca4/white-red/top.webp', FALSE, 'top'),
    (10, 7, '/dc/teknic/blue/angle-double.webp', TRUE, 'angle-double'),
    (10, 7, '/dc/teknic/blue/down.webp', FALSE, 'down'),
    (10, 7, '/dc/teknic/blue/left.webp', FALSE, 'left'),
    (10, 7, '/dc/teknic/blue/right.webp', FALSE, 'right'),
    (10, 7, '/dc/teknic/blue/top.webp', FALSE, 'top'),
    (10, 10, '/dc/teknic/green/angle.webp', TRUE, 'angle'),
    (10, 10, '/dc/teknic/green/down.webp', FALSE, 'down'),
    (10, 10, '/dc/teknic/green/left.webp', FALSE, 'left'),
    (10, 10, '/dc/teknic/green/right.webp', FALSE, 'right'),
    (10, 10, '/dc/teknic/green/top.webp', FALSE, 'top'),
    (11, 6, '/dc/anvil/angle-double.webp', TRUE, 'angle-double'),
    (11, 6, '/dc/anvil/down.webp', FALSE, 'down'),
    (11, 6, '/dc/anvil/left.webp', FALSE, 'left'),
    (11, 6, '/dc/anvil/right.webp', FALSE, 'right'),
    (11, 6, '/dc/anvil/top.webp', FALSE, 'top'),
    (12, 5, '/dc/manual/black-gum/angle.webp', TRUE, 'angle'),
    (12, 5, '/dc/manual/black-gum/down.webp', FALSE, 'down'),
    (12, 5, '/dc/manual/black-gum/left.webp', FALSE, 'left'),
    (12, 5, '/dc/manual/black-gum/right.webp', FALSE, 'right'),
    (12, 5, '/dc/manual/black-gum/top.webp', FALSE, 'top'),
    (13, 3, '/dc/crisis2/black/angle.webp', TRUE, 'angle'),
    (13, 3, '/dc/crisis2/black/down.webp', FALSE, 'down'),
    (13, 3, '/dc/crisis2/black/left.webp', FALSE, 'left'),
    (13, 3, '/dc/crisis2/black/right.webp', FALSE, 'right'),
    (13, 3, '/dc/crisis2/black/top.webp', FALSE, 'top');

INSERT INTO stock (model_id, size_id, color_id, quantity, price) -- check model -> color
VALUES
    (1, 19, 3, 1, 5000),
    (1, 19, 7, 1, 5000),
    (1, 19, 11, 1, 6000),
    (2, 19, 1, 2, 5450),
    (2, 19, 5, 2, 5450),
    (2, 19, 12, 3, 5200),
    (3, 19, 3, 1, 7150),
    (4, 19, 1, 1, 7150),
    (4, 19, 3, 1, 7150),
    (4, 19, 10, 2, 7300),
    (5, 19, 1, 3, 6400),
    (5, 19, 2, 3, 6400),
    (5, 19, 5, 3, 6400),
    (5, 19, 6, 3, 6400),
    (5, 19, 7, 3, 6400),
    (5, 19, 10, 4, 6320),
    (5, 19, 13, 4, 6320),
    (6, 19, 10, 4, 6320),
    (7, 19, 16, 4, 6320),
    (8, 19, 8, 2, 7150),
    (8, 19, 10, 1, 8350),
    (8, 19, 11, 1, 8350),
    (8, 19, 13, 1, 8350),
    (9, 19, 3, 2, 7600),
    (9, 19, 4, 2, 7600),
    (9, 19, 8, 2, 7600),
    (9, 19, 9, 2, 7600),
    (9, 19, 11, 1, 7400),
    (9, 19, 13, 1, 7400),
    (9, 19, 14, 1, 7400),
    (9, 19, 15, 1, 7400),
    (10, 19, 7, 1, 7400),
    (10, 19, 10, 3, 7500),
    (11, 19, 6, 2, 6750),
    (12, 19, 5, 2, 6750),
    (13, 19, 3, 2, 6750);